### ISSUE TITLE
contaiment cell console broken on pilar of spirit

### ISSUE THREAD

**Issue by Mikisx1** [tgstation/TerraGov-Marine-Corps#13067]
### Description

the contaiment cell console in pillar of spririt ship is broken and i dont know if its broken in other ship

### Test Merges

Round ID: [21298](https://scrubby.melonmesa.com/round/21298)
BYOND Version: 515.1607
Server revision compiled on: 
Master commit: [7010838a8005c20f67af42901b4d83643bd6dd0e](https://github.com/tgstation/TerraGov-Marine-Corps//commit/7010838a8005c20f67af42901b4d83643bd6dd0e)
The following pull requests are currently test merged:
[#12892: 'Adds a delay to throwing' by ivanmixo at commit a99898c494](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12892)
[#12990: 'Autocannon rework MK2' by Pariah919 at commit 75d34f1c10](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12990)
[#13004: 'Text to speech' by TiviPlus at commit a22aa9b047](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13004)
[#12977: 'Reworks boiler into having to be rooted to fire' by ivanmixo at commit 2359b3ebfd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12977)
[#12834: 'AI notification update' by RipGrayson at commit 52de572d7b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12834)

Local commit: a2026d18e137f679e5bfb63848cd4707d7fc80a4
Server tools version: 5.12.1

### Reproduction Steps

1 go to research contaiment celll
2 contaiment cell console is broken 
3 console cant be acesed or repaired

### Screenshots

![Screenshot_1](https://github.com/tgstation/TerraGov-Marine-Corps/assets/124826752/d39269a7-101d-46e1-8179-923fdb1d6d43)

**Comment by coldironwarrior** [comment]
fixed by #13258

**Comment by Mikisx1** [comment]
![not fully fixed](https://github.com/tgstation/TerraGov-Marine-Corps/assets/124826752/9502276d-1605-4788-b6b7-2c0eb03ecdeb)
well not fully it still dosent open the cell
